version: "3"

services:
  db:
    container_name: zaval_backend_db
    hostname: zaval_backend_db
    environment:
      POSTGRES_DB: zaval_backend_test
      POSTGRES_USER: zaval_backend
      POSTGRES_PASSWORD: 1
    image: "postgres:15.1-alpine"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "5433:5432"