# swagger
springdoc:
  swagger-ui.path: /swagger-ui.html
  api-docs.path: /api-docs
  packages-to-scan: org.home.zaval.zavalbackend
  paths-to-match: /**

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  web:
    resources:
      static-locations: file:./zaval-frontend
  flyway:
    locations: "classpath:db/migration"